// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include "Viewer.h"

Fl_Menu_Item PositViewer::menu_X[] = {
 {"Posit", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Float", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Double", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"GMP", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Item PositViewer::menu_Y[] = {
 {"Posit", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Float", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Double", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"GMP", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Item PositViewer::menu_Operator[] = {
 {"+", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"*", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"/", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

PositViewer::PositViewer() {
  { mainWindow = new Fl_Double_Window(536, 574, "PositViewer");
    mainWindow->user_data((void*)(this));
    { Fl_Group* o = new Fl_Group(30, 170, 480, 390, "ViewerDisplay");
      o->box(FL_EMBOSSED_BOX);
      { Fl_Scroll* o = new Fl_Scroll(40, 179, 465, 372);
        { new Fl_Box(40, 179, 460, 372, "ViewBox");
        } // Fl_Box* o
        o->end();
      } // Fl_Scroll* o
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(25, 21, 480, 124, "ControlWidgets");
      o->box(FL_SHADOW_FRAME);
      { Fl_Counter* o = new Fl_Counter(30, 32, 135, 35, "PositSize");
        o->minimum(1);
        o->maximum(32);
        o->step(1);
        o->value(6);
      } // Fl_Counter* o
      { Fl_Counter* o = new Fl_Counter(30, 82, 135, 35, "ES");
        o->minimum(0);
        o->maximum(32);
        o->step(1);
        o->value(2);
      } // Fl_Counter* o
      { Fl_Choice* o = new Fl_Choice(245, 35, 90, 25, "X-Number");
        o->down_box(FL_BORDER_BOX);
        o->menu(menu_X);
      } // Fl_Choice* o
      { Fl_Choice* o = new Fl_Choice(245, 70, 90, 25, "Y-Number");
        o->down_box(FL_BORDER_BOX);
        o->menu(menu_Y);
      } // Fl_Choice* o
      { Fl_Choice* o = new Fl_Choice(245, 105, 90, 25, "Operator");
        o->down_box(FL_BORDER_BOX);
        o->menu(menu_Operator);
      } // Fl_Choice* o
      { Fl_Value_Input* o = new Fl_Value_Input(375, 36, 130, 29, "Min");
        o->minimum(-1e+18);
        o->maximum(1e+18);
        o->value(-100);
      } // Fl_Value_Input* o
      { Fl_Value_Input* o = new Fl_Value_Input(375, 71, 130, 29, "Max");
        o->minimum(-1e+18);
        o->maximum(1e+18);
        o->value(100);
      } // Fl_Value_Input* o
      { Fl_Value_Input* o = new Fl_Value_Input(375, 106, 130, 29, "Step");
        o->minimum(-1e+18);
        o->maximum(1e+18);
        o->value(100);
      } // Fl_Value_Input* o
      o->end();
    } // Fl_Group* o
    mainWindow->end();
  } // Fl_Double_Window* mainWindow
}

void PositViewer::show() {
  mainWindow->show();
}
